### ISSUE TITLE
How to avoid printing "Warning: the nameservers did not answer"? 

### ISSUE THREAD

**Issue by KongNan** [wesinator/pynslookup#2]
I want to parse some hostname to ip, but while I print the ips_record.answer, I also get some "Warning: the nameservers did not answer".   How to avoid print that Warning? Thank you!

**Comment by wesinator** [comment]
Hi, 

This is printed from an exception when the DNS query nameservers do not respond https://github.com/wesinator/pynslookup/blob/fd373d645f80fa0dc49674f90944f0003766873f/nslookup/nslookup.py#L38 

There is no way currently to disable this from printing (unless you change the code and remove the print statement).

The records will still return an empty field.

Regards,

**Comment by wesinator** [comment]
I updated it so warnings will now go to stderr

Thanks for bringing this up, I started to notice it as well.
